server:
  port: 8088
  servlet:
    context-path: /api/v1
spring:
  application:
    name: furniture
  datasource:
    url: "jdbc:mysql://localhost:3306/store"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true