server:
  port: 8088
  servlet:
    context-path: /api/v1
spring:
  application:
    name: furniture
  datasource:
    url: "jdbc:mysql://localhost:3306/store"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signer-key: WX18auptfEsbPZoT76tdwU3EPMbGKa7ien8RxT8RLqbVzI7kpxdGjmD+FsrXN460
  valid-duration: 86400